services:
  app_proxy:
    environment:
      APP_HOST: franco-ts6_app_1
      APP_PORT: 9987
  app:
    image: teamspeaksystems/teamspeak6-server:latest
    restart: unless-stopped
    ports:
      - "9987:9987/udp"
      - "30033:30033/tcp"
    environment:
      - TSSERVER_LICENSE_ACCEPTED=accept
    volumes:
      - ts6-data:/var/tsserver
volumes:
  ts6-data:
