services:
  app:
    image: teamspeaksystems/teamspeak6-server:latest
    restart: unless-stopped
    ports:
      - "9987:9987/udp"
      - "30033:30033/tcp"
    environment:
      - TSSERVER_LICENSE_ACCEPTED=accept
      - TSSERVER_QUERY_SSH_ENABLED
      - TSSERVER_QUERY_SSH_PORT=10022
      - TSSERVER_QUERY_ALLOW_LIST=allow.txt
    volumes:
      - ts6-data:/var/tsserver
volumes:
  ts6-data:
